### ISSUE TITLE
Include tag?

### ISSUE THREAD

**Issue by arjan** [edgurgel/solid#100]
I see some reference to [include tags](https://hexdocs.pm/solid/Solid.FileSystem.html#content) however, are they actually implemented?
Also not sure if this is actually feasible using a custom tag because ideally we'd want to do the template inclusion in parse time and not in runtime?

**Comment by edgurgel** [comment]
Hey @arjan ! It's a typo! It should reference the `render` tag which we implement!

The include tag has been deprecated so we don't support it https://shopify.github.io/liquid/tags/template/ . We are aiming to follow Liquid's latest version until we reach 1.0.0 which by then we will probably lock a specific major version etc.

We do implement `render `though! AFAIK render will read the templates during parsing using your configured filesystem (which could be an actual filesystem or whatever database or S3 backed filesystem).

**Comment by arjan** [comment]
Ah yes `{% render %}` is what I was looking for. Strange that I did not see it :-) Makes sense now!

**Comment by edgurgel** [comment]
Perfect! TBH Solid's README needs to show off more what we can do already! It's getting pretty close to support everything the gem does
