### ISSUE TITLE
Possible to tell if a tag doesn't get a value?

### ISSUE THREAD

**Issue by sb8244** [edgurgel/solid#101]
Apologies for using the issue tracker for help. 

I am wondering if you see any way to detect whether a tag results in no value? I have a use case where I want to display an error (or even the `{{ name }}` text) if a value isn't available.

I attempted to look down the path of providing my own Solid.Context struct, but I don't think there is a place that I could hook in (even hacky) to detect an empty value.

**Comment by edgurgel** [comment]
Strict variables has been implemented #105 . I've created an issue for strict filters: https://github.com/edgurgel/solid/issues/107
