### ISSUE TITLE
date filter is incomplete

### ISSUE THREAD

**Issue by swbradshaw** [edgurgel/solid#118]
The date filter should accept parameters from the [Unix strftime](https://man7.org/linux/man-pages/man3/strftime.3.html), which includes `%s`.  `%s` outputs the number of seconds since Epoch (Jan 1, 1970_.  This does not appear to be supported in this library.  Are there plans to support this?

**Comment by edgurgel** [comment]
Yup if this is what the original Liquid gem supports we should definitely go for it!

**Comment by swbradshaw** [comment]
I made some progress to make this work!

https://github.com/elixir-lang/elixir/pull/12380

**Comment by swbradshaw** [comment]
This *should* be possible now with the latest version of Elixir. I have not tried it yet.

**Comment by edgurgel** [comment]
Yup it works with Elixir 1.16  1.17

https://github.com/edgurgel/solid/commit/f34e0e6152d64cf429d1163b4d2116e807ce24cb
