### ISSUE TITLE
Rendering options are not documented fully in the code

### ISSUE THREAD

**Issue by a3kov** [edgurgel/solid#125]
In the README you mention

> Solid.render/3 doesn't raise or return errors unless strict_variables: true or strict_filters: true are passed as options.

But the function doc doesn't mention it. IMO, README should not be mandatory read, code docs always take precedence as the source of truth

**Comment by edgurgel** [comment]
Yup! Agreed! Feel free to send a PR with extra docs that would've helped 👍
