### ISSUE TITLE
Consider breaking out built-in matchers into a separate dependency

### ISSUE THREAD

**Issue by nikcorg** [edgurgel/solid#136]
Hello,

We've been using a forked version of this library for a while for various reasons, which creates (for us) an extra maintenance burden.

Some of the features why we originally forked have since been merged back into this upstream version (thank you!), but in doing so, we also shot ourselves in the foot; the final reason we can't use the mainline version of this library, are the built-in matchers – that, ironically, my colleague contributed some time ago.

In our application we need to have a custom matcher for the Map type, due to reasons. I've tried to find smarter ways to allow overriding all or individual protocol implementations, but as far as I can tell there aren't any elegant solutions. ~Apart from maybe conditional compilation.~

Would you consider breaking out the built in matchers into a separate library, so that consumers of it could bring their own implementation? Alternatively, if you know of smarter, less drastic ways to support customising the built-in matchers, I'd be keen to hear about those too.

Being fully aware this is an "us problem", do let me know if there's anything I can do to help deliver this change. I'm more than happy to help in any way I can.

**Comment by edgurgel** [comment]
My first thought was to accept an option on Solid.render where it could define which "Matcher" we would like to use where the default is `Solid.Matcher`. This could be set as part of the `%Context{matcher_module: ...}` so that when `get_from_scope` is called it can pick which module will be called

```elixir
  defp get_from_scope(context, :vars, key) do
    context.matcher_module.match(context.vars, key)
  end

  defp get_from_scope(context, :counter_vars, key) do
    context.matcher_module.match(context.counter_vars, key)
  end

  defp get_from_scope(context, :iteration_vars, key) do
    context.matcher_module.match(context.iteration_vars, key)
  end
```

Would that work for your use-case?

**Comment by nikcorg** [comment]
@edgurgel I have a PR in the making, which solves the problem. It's potentially a bit dramatic, but you can be the judge of that. I'll do some testing on it before I submit (we'll keep the change on our fork either way), but should be with you this week.
