### ISSUE TITLE
Context Value Keys

### ISSUE THREAD

**Issue by barkerja** [edgurgel/solid#14]
@edgurgel How do you feel about the following:

Instead of the parser returning `{:field, String.t()}` it returns `{:field [atom()]}`. This would remove the need to split the string during render/runtime and also play nicely with structs without the need for any coercion.

I feel enforcing keys as atoms is more beneficial than strings, due to the fact you gain the ability to use structs for your render values.

The parser would become:
```erlang
field    <- [0-9a-zA-Z\._]* access* `
 case Node of
   [FieldName | [[]]] -> {field, lists:map(fun(Field) -> binary_to_existing_atom(Field, utf8) end, string:split(iolist_to_binary(FieldName), "."))};
   [FieldName | [Accesses]] ->
     {field, lists:map(fun(Field) -> binary_to_existing_atom(Field, utf8) end, string:split(iolist_to_binary(FieldName), ".")), Accesses}
 end
`;
```

And the argument:
```elixir
@spec get({:field, [atom()]} | {:field, [atom()], [{:access, non_neg_integer}]} | {:value, term}, Context.t) :: term
def get({:value, val}, _hash), do: val
def get({:field, key}, %Context{vars: vars}) do
  get_in(vars, key)
end
```

**Comment by edgurgel** [comment]
The problem with using atoms here is that a very common use case is to receive templates from users. So this would force us to have that atom defined right? And if we don't use `to_existing...` we could allocate too many atoms etc. 

We could split the string at parsing time also right? Given that `get_in` works with both? Or am I mixing things up? 🤔

**Comment by barkerja** [comment]
> We could split the string at parsing time also right? Given that get_in works with both? Or am I mixing things up?
That's correct. `get_in/2` can take practically any (container) type that implements the `Access` protocol (keyword, map, struct) as its first argument, but does require a list as its second argument.

> The problem with using atoms here is that a very common use case is to receive templates from users.
I think I'd need an example of this as I'm don't quite follow.

> So this would force us to have that atom defined right? And if we don't use to_existing... we could allocate too many atoms etc.
That's correct.

**Comment by edgurgel** [comment]
> That's correct. get_in/2 can take practically any (container) type that implements the Access protocol (keyword, map, struct) as its first argument, but does require a list as its second argument.

So what if we just ensure on the parser level that we will always return a list with strings for the access? So if it's a simple `field -> ["field"]` and if it's a `field1.field2 -> ["field1", "field2"]`

What do you think?

> The problem with using atoms here is that a very common use case is to receive templates from users.

Say for example you have an e-mail company that wants to accept liquid templates to be rendered when an e-mail is sent. The template is provided by the user with fields that we will try to convert to Atom. The template may have any kind of field that the Elixir code haven't used yet. So it will fail if `binary_to_existing_atom` is called.

That's what I understand that it will happen if we try to convert to Atom at that point.

**Comment by barkerja** [comment]
> So what if we just ensure on the parser level that we will always return a list with strings for the access? So if it's a simple field -> ["field"] and if it's a field1.field2 -> ["field1", "field2"]
👍 I'll submit a PR for this soon!

> Say for example you have an e-mail company that wants to accept liquid templates to be rendered when an e-mail is sent. The template is provided by the user with fields that we will try to convert to Atom. The template may have any kind of field that the Elixir code haven't used yet. So it will fail if binary_to_existing_atom is called.
Thank you for that example. Helped me understand other use cases (which is a large departure from how we _currently_ use solid). I've rethought the problem and determined is best if we use the Access behaviour for our structs which will enable them to behave with `get_in/2`

**Comment by edgurgel** [comment]
Nice! 🎉

**Comment by barkerja** [comment]
Closing this now with https://github.com/edgurgel/solid/pull/15
