### ISSUE TITLE
Custom block tags

### ISSUE THREAD

**Issue by edgurgel** [edgurgel/solid#43]
```liquid
{% navigation %}
  {% link About %}
  {% link Services %}
  {% link Contact %}
{% endnavigation %}
```

**Comment by sb8244** [comment]
I was looking to implement the `paginate` tag like Shopify does. This would be considered a block tag.

I can make the start/end block right now via custom parser/tag, but does a custom tag get the ability to modify the vars? I'd like to add a `paginate` object when pagination is opened, and close it in `endpaginate`.

**Comment by sb8244** [comment]
Digging into the [code a bit](https://github.com/edgurgel/solid/blob/master/lib/solid/tag.ex#L35), that may be possible if `context` is returned from a tag. If a certain format is returned, maybe the tag could update the context and set the text?

**Comment by edgurgel** [comment]
Yeah I think it makes sense for a custom tag to be able to do so
