### ISSUE TITLE
Custom tag with arguments

### ISSUE THREAD

**Issue by sb8244** [edgurgel/solid#48]
Is it possible to pass arguments into a custom tag? For example: Shopify's render tag allows for this syntax:

```
{% render 'name', my_variable: my_variable, my_other_variable: 'oranges' %}
```

I've tried this out and it doesn't seem possible today, although I could be missing something.

**Comment by bluzky** [comment]
As I see, currently Solid only allow positional argument or named argument. We can not use both at the same time.
