### ISSUE TITLE
Issue with filters not applied

### ISSUE THREAD

**Issue by sb8244** [edgurgel/solid#58]
This is a super strange one that gets into some stuff I'm not sure about. I am seeing filters not being applied, sometimes, which made me look into root cause.

### Symptoms

I see the input to my filter appear when I restart the server. The filter is not applied.

Running `MyCustomFilters.the_filter("x")` properly returns the filter result. The solid filter is now applied every time.

### Root Cause

I tracked it down to `String.to_existing_atom` raising an error for my function:

```
iex(9)> String.to_existing_atom("asset_url")
** (ArgumentError) argument error
    :erlang.binary_to_existing_atom("asset_url", :utf8)
```

After I manually run the function, it becomes an existing atom. TBH, I'm not entirely sure what causes a function to be registered as an atom, and I'm not sure why it's not an existing atom when the app first boots.

**Comment by sb8244** [comment]
It looks like this is just how modules work: https://github.com/elixir-lang/elixir/issues/4832#issuecomment-227099444

It may be necessary for me to add this to `application.ex`: `Code.ensure_loaded(My.CustomFilters)`

**Comment by edgurgel** [comment]
Interesting! I wonder if this will be a common issue and if we could avoid it? Or maybe documenting could be enough? 🤔

**Comment by edgurgel** [comment]
https://github.com/edgurgel/solid/pull/132
