### ISSUE TITLE
ArgumentError when using `contains` if `:contains` hasn't been used.

### ISSUE THREAD

**Issue by iautom8things** [edgurgel/solid#71]
There's an issue if  you use the `contains` operator due to the use of `:erlang.binary_to_existing_atom`.

<img width="823" alt="Screen Shot 2021-05-28 at 12 02 31 PM" src="https://user-images.githubusercontent.com/522040/120018319-9e892400-bfac-11eb-8d98-bd609476f1c1.png">

I'm opening this issue instead of a PR because I'm not sure what the best route would be to solve this.  There's an easy workaround that makes this a non-blocking issue, for me: 

Simply defining `:contains` _somewhere_ "fixes" this for me, but I think ideally this module should somehow ensure that `:contains` already exists.

I've seen `@before_compile` used for this or just as a no-op line proceeding the usage of `:erlang.binary_to_existing_atom`

**Comment by barkerja** [comment]
Any reason to not just change [:erlang.binary_to_existing_atom/1](https://github.com/edgurgel/solid/blob/c4a9f3f44354ef5b04acf2ccc7e9245c9dfeab47/lib/solid/parser.ex#L242) to `:erlang.binary_to_atom/1`, given that this isn't user-supplied data?

**Comment by edgurgel** [comment]
Yeah I think @barkerja is right here. Using binary_to_atom should do the job for this case 👌
