### ISSUE TITLE
Add missing filters

### ISSUE THREAD

**Issue by edgurgel** [edgurgel/solid#8]
Missing filters:

* [x] at_most
* [x] at_least
* [x] date
* [x] modulo https://github.com/edgurgel/solid/pull/54
* [x] newline_to_br https://github.com/edgurgel/solid/pull/56
* [x] strip_html https://github.com/edgurgel/solid/pull/57
* [x] strip_newlines https://github.com/edgurgel/solid/pull/56
* [x] where https://github.com/edgurgel/solid/pull/55
* [x] [escape](https://shopify.github.io/liquid/filters/escape/)
* [x] [escape_once](https://shopify.github.io/liquid/filters/escape_once/)
* [x] [concat](https://shopify.github.io/liquid/filters/concat/)
* [x] [url_decode](https://shopify.github.io/liquid/filters/url_decode/)
* [x] [url_encode](https://shopify.github.io/liquid/filters/url_encode/)

**Comment by barkerja** [comment]
@edgurgel How do you feel about support for custom filters? I was thinking a configuration that allows for defining a module. `Solid.Filter` would check for this configuration, importing module and its definitions if it exists.

This would allow for some more complex filters that may fall outside the scope of what the liquid spec defines, and also control dependencies (ex: an integrator may want to use `Timex` to format dates, but Solid should not have it as a hard dep).

**Comment by LostKobrakai** [comment]
`date` could use https://github.com/plataformatec/nimble_strftime. It doesn't depend on any additional libraries and only does formatting.

**Comment by edgurgel** [comment]
@LostKobrakai that's pretty handy Thanks for the tip!  👍

**Comment by sb8244** [comment]
Wasn't sure if this is the right place to track it, but I'm wondering if `.size` should be support in if tag?

![image](https://user-images.githubusercontent.com/1231659/95409611-07257280-08f0-11eb-80a7-9b47de1c2fe1.png)

**Comment by edgurgel** [comment]
@sb8244 it should be supported yes! . Thanks for bringing this up! Issue created: https://github.com/edgurgel/solid/issues/47

**Comment by wmnnd** [comment]
@edgurgel Would you be open to a PR that implements the `date` filter with Elixir 1.11’s new ` Calendar.strftime/3` function?

**Comment by edgurgel** [comment]
@wmnnd 100%! Then we just bump the elixir requirement accordingly 😎

**Comment by wmnnd** [comment]
@edgurgel Awesome! I’ll create a PR tomorrow.

**Comment by LostKobrakai** [comment]
I've just added PRs for the rest besides `strip_html`. `strip_newlines` and `newlines_to_br` are naive implementations right now however, as they do not retain the iolist of the supplied template, but normalize to a binary.

**Comment by LostKobrakai** [comment]
It seems like the current CI build is broken because the `where` filter was only added on 4.0.2, while CI uses `4.0.0`

**Comment by edgurgel** [comment]
Thanks for the heads up! Speaking of CI I should move this to GHA one day 🤔

**Comment by edgurgel** [comment]
I've just updated the ticket with the remaining filters (they were added after I've originally created this issue):

`escape`
 `escape_once`
 `concat`
`prepend`
 `url_decode`
 `url_encode`

**Comment by Jcambass** [comment]
I Will prepare a patch for `concat` and `prepend` later today.

**Comment by edgurgel** [comment]
@Jcambass yes you are right! My bad! 🤦

**Comment by LostKobrakai** [comment]
I'm already on the two missing filters. Just need to look into `escape_once`. Seems like `Plug.HTML` does currently only do raw escaping.

**Comment by edgurgel** [comment]
Thanks, everyone! 🎉
