### ISSUE TITLE
Pass options to custom tag

### ISSUE THREAD

**Issue by bluzky** [edgurgel/solid#80]
I read code which render `custom_tag` and I see that the options is not passed to custom tag render function.
Is there any reason not to do that?

In my case I want to add custom tag `render` to render another template, and I think it would be better to pass via `options` instead of variables.

For example:
```elixir
template
|> Solid.parse!()
|> Solid.render(my_variables, tags: %{"include" => MyIncludeTemplate}, lookup_dir: "templates/")
```

or we can support tag options tuple

```elixir
template
|> Solid.parse!()
|> Solid.render(my_variables, tags: %{"include" => {MyIncludeTemplate, [lookup_dir: "templates/"]})
```

**Comment by edgurgel** [comment]
Makes sense! We want to support `render` as a first class tag one day. The discussion on issue might help: https://github.com/edgurgel/solid/issues/38

**Comment by bluzky** [comment]
I have a concert regarding `render`. Implementing template lookup on rendering is quite easy but we can't handle template error like `parse/2`
I don't know if we can implement lookup and parse linked template with parser. Solid use `nimble_parsec` and from its document, that seems impossible.
