### ISSUE TITLE
Passing render options to Custom Filters

### ISSUE THREAD

**Issue by christopherlai** [edgurgel/solid#97]
Hi @edgurgel - thanks for creating this library for the community! What are your thoughts on passing the `options` passed to render down to the custom filters.

Use case:
In a multi-tenant environment, if I create a custom filter like `asset_url` (similar to the one Shopify offers), I need to know the tenant in order to return the correct URL. Additionally, filename passed to `asset_url` might have a hash appended to the name.

`{{ "logo.png" | asset_url }}` returns `https://cdn.com/logo-123abc-hash.png`.

Thanks!

**Comment by edgurgel** [comment]
Hi @christopherlai, 

I like the idea but I'm not sure how we would implement that 🤔 Do you have any idea in mind? Passing options as the last argument to all filters?

**Comment by christopherlai** [comment]
My initial thoughts is to have a `filters` keyword on the `opts` passed to `Argument.get`. The value of `filters` could be passed into `Filter.apply`. This would only be passed to custom filter as the last argument.

**Comment by christopherlai** [comment]
@edgurgel suggestions on backwards compatibility with existing custom filters? I thought of a few ways this could be handled.

1. Make this a breaking change, everyone needs to updates to their existing filters with one additional arity.
2. Make it a config option with opt-in/opt-out `config :solid, :custom_filters_opts, true`.
3. Use specific naming for filters with options `def asset_url` vs `def asset_url_with_opts`. Check for exported functions for both and the first one that matches gets applied
4. New configuration key, `custom_filters` for existing filters and `additional_filters` for filters with options

I think option 1 is the cleanest way forward of the package, but places the burden of work on the users of the package.

**Comment by edgurgel** [comment]
Cool I think the approach to change is fine but yeah we need to account for backwards compatibility. 

I was wondering if could do something similar to 3 but slightly different? Not sure if this might work but something along the lines of:

Given this tempalte

```
{{ "logo.png" | asset_url }}
```

We check if `assert_url/2` exists. If that's a yes we send options at the end. Otherwise we check if asset_url/1 exists and we don't send options.

Would that work ? 🤔 

And then down the line we might deprecate not passing options before 1.0.0 ?

**Comment by christopherlai** [comment]
Simple and straightforward, makes sense to me. I think what I missed is that the second argument is a named argument.
